import Mock from '../mock'

const ListDB = {
    list: [
        {
            id: 1,
            email: 'admin@gmail.com',
            userName: 'Nhat Truong',
            projectName: 'Matx development',
            date: new Date().toLocaleString(),
            projectImage: '/assets/images/products/headphone-2.jpg',
            userImage: '/assets/images/face-1.jpg',
            comment: 0,
            revision: 5,
        },
        {
            id: 2,
            email: 'admin@gmail.com',
            userName: 'Nhat Truong',
            projectName: 'Matx development',
            date: new Date().toLocaleString(),
            projectImage: '/assets/images/products/headphone-2.jpg',
            userImage: '/assets/images/face-1.jpg',
            comment: 0,
            revision: 5,
        },
        {
            id: 3,
            email: 'admin@gmail.com',
            userName: 'Nhat Truong',
            projectName: 'Matx development',
            date: new Date().toLocaleString(),
            projectImage: '/assets/images/products/headphone-3.jpg',
            userImage: '/assets/images/face-1.jpg',
            comment: 0,
            revision: 5,
        },
        {
            id: 5,
            email: 'admin@gmail.com',
            userName: 'Nhat Truong',
            projectName: 'Gull development',
            date: new Date().toLocaleString(),
            projectImage: '/assets/images/products/headphone-2.jpg',
            userImage: '/assets/images/face-1.jpg',
            comment: 0,
            revision: 5,
        },
        {
            id: 6,
            email: 'admin@gmail.com',
            userName: 'Nhat Truong',
            projectName: 'Evalynn development',
            date: new Date().toLocaleString(),
            projectImage: '/assets/images/products/iphone-1.jpg',
            userImage: '/assets/images/face-1.jpg',
            comment: 0,
            revision: 5,
        },
        {
            id: 7,
            email: 'admin@gmail.com',
            userName: 'Nhat Truong',
            projectName: 'Dexum development',
            date: new Date().toLocaleString(),
            projectImage: '/assets/images/products/headphone-2.jpg',
            userImage: '/assets/images/face-1.jpg',
            comment: 0,
            revision: 5,
        },
        {
            id: 8,
            email: 'admin@gmail.com',
            userName: 'Nhat Truong',
            projectName: 'Matx development',
            date: new Date().toLocaleString(),
            projectImage: '/assets/images/products/headphone-3.jpg',
            userImage: '/assets/images/face-1.jpg',
            comment: 0,
            revision: 5,
        },
        {
            id: 9,
            email: 'admin@gmail.com',
            userName: 'Nhat Truong',
            projectName: 'Matx development',
            date: new Date().toLocaleString(),
            projectImage: '/assets/images/products/headphone-3.jpg',
            userImage: '/assets/images/face-1.jpg',
            comment: 0,
            revision: 5,
        },
    ],
}

Mock.onGet('/api/list/all').reply((config) => {
    const response = ListDB.list
    return [200, response]
})
